#!/bin/bash

#Set fonts for Help.
NORM=`tput sgr0`
BOLD=`tput bold`
REV=`tput smso`
#Set Script Name variable
SCRIPT=`basename ${BASH_SOURCE[0]}`

PWD=`pwd`
MACHINE=gmunu
PROBLEM=hii3d

if [ $MACHINE = "jgkim" ]; then
    ATHENADIR="/home/jgkim/athena/"
    MAKE="/home/jgkim/dotfiles/colormake/colormake.sh" # colorize output of gcc
elif [ $MACHINE = "gmunu" ]; then
    ATHENADIR="/home/jgkim/athena/"
    MAKE="/home/jgkim/dotfiles/colormake/colormake.sh" # colorize output of gcc
fi


#Initialize variables to default values.
DEBUG="--with-cflags=opt"
MPI=
MPIPRINT="disabled"

#Help function
function HELP {
  echo -e \\n"*athena configure and compile bash script" 
  echo "Command line switches are optional. The following switches are recognized."
  echo "${REV}-m${NORM}  --Sets the value for configure option ${BOLD}--enable-mpi${NORM}. Default is ${BOLD}none${NORM}."
  echo "${REV}-d${NORM}  --Sets the value for configure option ${BOLD}--cflags-debug=debug${NORM}. Default is ${BOLD}--cflags-debug=opt${NORM}."
  echo -e "${REV}-h${NORM}  --Displays this help message. No further functions are performed."\\n
  echo -e "Example: ${BOLD}./$SCRIPT -dm${NORM}"\\n
  exit 1
}

while getopts :dmh FLAG; do
  case $FLAG in
    d)  #set option "d"
      DEBUG="--with-cflags=debug"
      ;;
    m)  #set option "m"
      MPI="--enable-mpi"
      MPIPRINT=$MPI
      ;;
    h)  #show help
      HELP
      exit 0
      ;;
    \?) #unrecognized option - show help
      echo -e "Option -${BOLD}$OPTARG${NORM} not allowed."
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

cd $ATHENADIR
$MAKE clean -j
$MAKE clean -j
./configure --with-gas=hydro --with-flux=hllc --with-integrator=vl --with-order=2p --enable-point-source --with-problem=$PROBLEM $DEBUG $MPI

$MAKE all -j MACHINE=$MACHINE

cd $PWD

echo "================================================"
echo " Athena configure and compile done with options:"
echo " - machine: $MACHINE"
echo " - problem: $PROBLEM"
echo " - mpi: $MPIPRINT"
echo " - debug: $DEBUG"
echo "================================================"

exit 0
